t = range(3, 7)
print(t)
print(" This range contains ", len(t), "elements")
print("Element at index [0]", t[0])
# print(t+t)
# print(t*4)
print("The elements of range between index [3] and [5]", t[3:5])
